CreditManagement/urls.py
from django.urls import path

from CreditManagement.views import MoneyObtainmentView, TransactionAddView, TransactionFinalisationView, \
    TransactionListView

app_name = 'credits'

urlpatterns = [
    path('transactions/', TransactionListView.as_view(), name='transaction_list'),
    path('transactions/add', TransactionAddView.as_view(), name='transaction_add'),
    path('finalise_transactions/', TransactionFinalisationView.as_view(), name='transactions_finalise'),
    path('dining_money/', MoneyObtainmentView.as_view(), name='dining_money')
]

Dining/urls.py
from django.urls import include, path

from . import views
from .views import DayView, index

urlpatterns = [
    path('', index, name='index'),
    path('csv/', views.DailyDinersCSVView.as_view(), name="diners_csv"),
    path('<int:day>/<int:month>/<int:year>/', include([
        path('', DayView.as_view(), name='day_view'),
        path('add/', views.NewSlotView.as_view(), name='new_slot'),
        path('<slug:identifier>/', include([
            path('', views.SlotInfoView.as_view(), name='slot_details'),
            path('list/', views.SlotListView.as_view(), name='slot_list'),
            path('allergy/', views.SlotAllergyView.as_view(), name='slot_allergy'),
            path('entry/add/', views.EntryAddView.as_view(), name='entry_add'),
            path('change/', views.SlotInfoChangeView.as_view(), name='slot_change'),
            path('delete/', views.SlotDeleteView.as_view(), name='slot_delete'),
            path('inform_payment/', views.SlotPaymentView.as_view(), name='slot_inform_payment'),
        ])),
    ])),
    path('entries/<int:pk>/delete/', views.EntryDeleteView.as_view(), name='entry_delete'),
]

creditmanagement/urls.py
from django.urls import include, path

from creditmanagement.views import (
    TransactionAddView,
    TransactionCSVView,
    TransactionListView,
)

app_name = "credits"

urlpatterns = [
    path(
        "transactions/",
        include(
            [
                path("", TransactionListView.as_view(), name="transaction_list"),
                path("add/", TransactionAddView.as_view(), name="transaction_add"),
                path(
                    "csv/<int:pk>/",
                    TransactionCSVView.as_view(),
                    name="transaction_csv",
                ),
            ]
        ),
    ),
]

scaladining/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("credit/", include("creditmanagement.urls")),
    path("site/", include("general.urls")),
    path("reports/", include("reports.urls")),
    path("", include("dining.urls")),
    path("accounts/", include("userdetails.urls")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

creditmanagement/forms.py
from typing import Any, Tuple

from dal_select2.widgets import ModelSelect2
from django import forms
from django.core.exceptions import ValidationError
from django.db import transaction

from creditmanagement.models import Account, Transaction
from general.mail_control import send_templated_mail
from userdetails.models import Association, User

# Form fields which are used in transaction forms
USER_FORM_FIELD = forms.ModelChoiceField(
    User.objects.filter(is_active=True),
    required=False,
    widget=ModelSelect2(url="people_autocomplete"),
    label="User",
)
ASSOCIATION_FORM_FIELD = forms.ModelChoiceField(
    Association.objects.all(), required=False, label="Association"
)
SPECIAL_FORM_FIELD = forms.ModelChoiceField(
    Account.objects.filter(special__isnull=False),
    required=False,
    label="Bookkeeping account",
)


def one_of(*args) -> Tuple[Any, int]:
    """Returns the element and index of the one argument that evaluates to True.

    If multiple or none of the arguments evaluate to True, (None, -1) is returned.
    """
    el = None
    idx = -1
    for i in range(len(args)):
        if args[i]:
            if el:
                return (
                    None,
                    -1,
                )  # Another True element was already found so multiple evaluate to True
            el = args[i]
            idx = i
    return el, idx


class TransactionForm(forms.ModelForm):
    """Allows creating transactions from a set source to a user or association target.

    Blocks a transaction if a user's account balance becomes negative.
    """

    origin = forms.CharField(disabled=True)
    target_user = USER_FORM_FIELD
    target_association = ASSOCIATION_FORM_FIELD

    class Meta:
        model = Transaction
        fields = [
            "origin",
            "amount",
            "target_user",
            "target_association",
            "description",
        ]
        help_texts = {
            "description": "E.g. deposit or withdrawal via board member.",
        }

    def __init__(self, source: Account, user: User, *args, **kwargs):
        """Constructor.

        Args:
            source: The account that is used as source of the transaction.
            user: The user who is creating the transaction.
        """
        super().__init__(*args, **kwargs)
        self.instance.source = source
        self.instance.created_by = user
        self.fields["origin"].initial = str(source)
        self.fields["target_association"].help_text = (
            "Provide a user or an association who will receive the money. "
            "You can't provide both a user and an association."
        )

    def clean(self):
        cleaned_data = super().clean()
        # Check that there's exactly 1 one user or association set
        target_el, idx = one_of(
            cleaned_data.get("target_user"), cleaned_data.get("target_association")
        )
        if not target_el:
            raise ValidationError("Provide exactly one of user or association.")

        # Set target of the transaction
        self.instance.target = target_el.account

        # Check target != source
        if self.instance.target == self.instance.source:
            raise ValidationError("Receiver cannot be the same as the origin.")

        # Check balance!!
        # We block transactions made by this form that make a user account balance negative
        # (Note that there's a race condition here, but it is not an issue in practice.)
        source = self.instance.source  # type: Account
        if source.user and source.get_balance() < cleaned_data.get("amount"):
            raise ValidationError("Your balance is insufficient.")

        return cleaned_data


class SiteWideTransactionForm(forms.ModelForm):
    """Allows creating transactions with arbitrary source and destination.

    Should only be used by bosses. An e-mail is sent to a user when money is
    withdrawn from their account.
    """

    source_user = USER_FORM_FIELD
    source_association = ASSOCIATION_FORM_FIELD
    source_special = SPECIAL_FORM_FIELD
    target_user = USER_FORM_FIELD
    target_association = ASSOCIATION_FORM_FIELD
    target_special = SPECIAL_FORM_FIELD

    class Meta:
        model = Transaction
        fields = [
            "source_user",
            "source_association",
            "source_special",
            "target_user",
            "target_association",
            "target_special",
            "amount",
            "description",
        ]

    def __init__(self, user: User, *args, **kwargs):
        """Constructor.

        Args:
            user: The user who is creating the transaction.
        """
        super().__init__(*args, **kwargs)
        self.instance.created_by = user

    def clean(self):
        """Converts the source and target fields into actual accounts."""
        cleaned_data = super().clean()
        # Get source
        source_el, source_idx = one_of(
            cleaned_data.get("source_user"),
            cleaned_data.get("source_association"),
            cleaned_data.get("source_special"),
        )
        if not source_el:
            raise ValidationError("Provide exactly 1 transaction source.")
        # Target
        target_el, target_idx = one_of(
            cleaned_data.get("target_user"),
            cleaned_data.get("target_association"),
            cleaned_data.get("target_special"),
        )
        if not target_el:
            raise ValidationError("Provide exactly 1 transaction target.")
        # Convert to actual accounts (in the case of a user or association object)
        self.instance.source = source_el if source_idx == 2 else source_el.account
        self.instance.target = target_el if target_idx == 2 else target_el.account

        # Check target != source
        if self.instance.target == self.instance.source:
            raise ValidationError("Receiver cannot be the same as the origin.")

        return cleaned_data

    def save(self, commit=True, request=None):
        """This method sends an email to the source user on save.

        Provide the request for email template rendering.
        """
        instance = super().save(commit=False)
        if commit:
            with transaction.atomic():
                # We do this in a DB transaction so that when the e-mail failed,
                # the transaction is not saved. (Not sure whether it's a good idea, but doesn't really matter)
                instance.save()
                # Send mail if the source is a user
                source = self.instance.source
                if source.user:
                    send_templated_mail(
                        "mail/transaction_created",
                        source.user,
                        {"transaction": instance},
                        request,
                    )

        return instance


class ClearOpenExpensesForm(forms.Form):
    """Creates transactions for all members of this association who are negative."""

    description = forms.CharField(
        max_length=150,
        help_text="Is displayed on each user's transaction overview, "
        "e.g. in the case of Quadrivium it could be 'Q-rekening'.",
    )

    def __init__(self, *args, association=None, user=None, **kwargs):
        # Calculate and create the transactions that need to be applied

        # Get all verified members. Probably nicer to create a helper method for this.
        members = User.objects.filter(
            # We could exclude inactive user accounts.
            # But they will show up in the association members list and can be rejected there manually.
            # is_active=True,
            usermembership__association=association,
            usermembership__is_verified=True,
        )
        self.transactions = []
        for m in members:
            balance = m.account.get_balance()
            if balance < 0:
                # Construct a transaction for each member with negative balance
                tx = Transaction(
                    source=association.account,
                    target=m.account,
                    amount=-balance,
                    created_by=user,
                )  # Description needs to be set later
                self.transactions.append(tx)
        super().__init__(*args, **kwargs)

    def save(self):
        """Saves the transactions to the database."""
        if not self.is_valid():
            raise RuntimeError
        desc = self.cleaned_data.get("description")
        with transaction.atomic():
            for tx in self.transactions:
                tx.description = desc
                tx.save()


# Todo! This form is currently not used, it can be removed
class AccountPickerForm(forms.Form):
    """Form that enables the user to choose any account of any type."""

    user = USER_FORM_FIELD
    association = ASSOCIATION_FORM_FIELD
    special = SPECIAL_FORM_FIELD

    def clean(self):
        cleaned_data = super().clean()
        fields = (
            bool(cleaned_data["user"]),
            bool(cleaned_data["association"]),
            bool(cleaned_data["special"]),
        )
        if sum(fields) != 1:
            raise ValidationError("Select 1 of the fields.")
        return super().clean()

    def get_account(self) -> Account:
        """Returns the account that was picked."""
        user = self.cleaned_data["user"]
        if user:
            return user.account
        association = self.cleaned_data["association"]
        if association:
            return association.account
        special = self.cleaned_data["special"]
        if special:
            return special
        raise RuntimeError

creditmanagement/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, StreamingHttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, View
from django.views.generic.list import ListView

from creditmanagement.forms import TransactionForm
from creditmanagement.models import Account, Transaction


class TransactionListView(LoginRequiredMixin, ListView):
    template_name = "credit_management/transaction_history.html"
    paginate_by = 20

    def get_queryset(self):
        return Transaction.objects.filter_account(self.request.user.account).order_by(
            "-moment"
        )


class TransactionCSVView(LoginRequiredMixin, View):
    """Returns a CSV with transactions."""

    def has_permission(self, account) -> bool:
        """Whether the current user has permission to download the CSV.

        * Normal users can only export their own account.
        * Association board members can export the association transactions.
        * Site-wide admins can export any account.

        Args:
            account: The account to export.
        """
        if self.request.user.has_site_stats_access():
            return True
        if account.user and account.user == self.request.user:
            return True
        if account.association and self.request.user.is_board_of(account.association):
            return True
        return False

    def get(self, request, *args, pk=None, **kwargs):
        account = get_object_or_404(Account, pk=pk)

        if not self.has_permission(account):
            raise PermissionDenied

        # Stream CSV
        qs = Transaction.objects.filter_account(account).order_by("-moment")
        return StreamingHttpResponse(
            qs.csv(),
            content_type="text/csv",
            headers={"Content-Disposition": 'attachment; filename="transactions.csv"'},
        )


class TransactionFormView(FormView):
    """Base class for a view with a create transaction form.

    A subclass needs to override get_source(), set the success URL and set the
    template name.
    """

    form_class = TransactionForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["source"] = self.get_source()  # Set transaction source/origin
        kwargs["user"] = self.request.user  # Set created_by
        return kwargs

    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request, messages.SUCCESS, "Transaction has been successfully created."
        )
        return HttpResponseRedirect(self.get_success_url())

    def get_source(self) -> Account:
        """Returns the source/origin for the transaction."""
        raise NotImplementedError


class TransactionAddView(LoginRequiredMixin, TransactionFormView):
    """View where a user can transfer money to someone else."""

    template_name = "credit_management/transaction_add.html"
    success_url = reverse_lazy("credits:transaction_list")

    def get_source(self) -> Account:
        return self.request.user.account


# MoneyObtainmentView is removed in favor of Site Credits tab

assets/templates/credit_management/balance_upgrade_assoc_snippet.html
<hr style="{% if border_color %}border-color: {{ border_color }};{% endif %}">
<div class="row">
    {# Association image #}
    <div class="col-md-2 d-none d-md-flex justify-content-center">
        {# (Image is in separate div so that it is inside of the column padding) #}
        {% if association.image %}
            <div class="slot_image w-100" style="background-image: url({{ association.image.url }});">
            </div>
        {% endif %}
    </div>

    <div class="col-md-10">
        <h4>{{ association.name }}</h4>
        <p>{{ association.balance_update_instructions|linebreaksbr }}</p>
    </div>
</div>

assets/templates/credit_management/balance_upgrade_instructions.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h3>
        Upgrading your balance
    </h3>
    <p>
        The boards of all associations using the kitchen can upgrade your balance.
        For convenience try to upgrade your balance at your association(s) first.
    </p>

    {% if user_associations %}
        {% for association in user_associations %}
            {% include "credit_management/balance_upgrade_assoc_snippet.html" %}
        {% endfor %}
        <hr>
        <p class="mt-4">
            You can also try to contact any of the other associations if necessary, but please do this as little as
            possible.
        </p>
    {% endif %}

    {% for association in other_associations %}
        {% include "credit_management/balance_upgrade_assoc_snippet.html" with border_color="#444" %}
    {% endfor %}
    <hr style="border-color: #444;">

{% endblock %}

assets/templates/credit_management/snippet_credit_history.html
{% load credit_tags %}
{% load humanize %}

<div class="row col-12 m-0 p-0 p-md-2 py-2">
    <div class="col-2 p-0">
        {{ transaction.order_moment|naturaltime }}
    </div>
    <div class="col-1 p-0">
        {% if transaction.source_user == user %}
            To
        {% else %}
            From
        {% endif %}
    </div>
    <div class="col-4 p-0">
        {% if transaction.source == user %}
            {{ transaction.target }}
        {% else %}
            {{ transaction.source }}
        {% endif %}
    </div>
    <div class="col-2 p-0">
        {% if transaction.source_user == user %}
            <span class="text-danger">{{ transaction.amount|negate|euro }}</span>
        {% else %}
            <span class="text-success">+{{ transaction.amount|euro }}</span>
        {% endif %}
    </div>
    <div class="col-3 p-0">
        {{ transaction.description }}
    </div>
</div>

assets/templates/credit_management/snippet_credit_history_association.html
{% load credit_tags %}
{% load humanize %}

<div class="row col-12 m-0 p-0 p-md-2 py-2">
    <div class="col-2 p-0">
        {{ transaction.order_moment|naturaltime }}
    </div>
    <div class="col-1 p-0">
        {% if transaction.source_association == association %}
            To
        {% else %}
            From
        {% endif %}
    </div>
    <div class="col-4 p-0">
        {% if transaction.source == association %}
            {{ transaction.target }}
        {% else %}
            {{ transaction.source }}
        {% endif %}
    </div>
    <div class="col-2 p-0">
        {% if transaction.source_association == association %}
            <span class="text-danger">{{ transaction.amount|negate|euro }}</span>
        {% else %}
            <span class="text-success">+{{ transaction.amount|euro }}</span>
        {% endif %}
    </div>
    <div class="col-3 p-0">
        {{ transaction.description }}
    </div>
</div>

assets/templates/credit_management/transaction_add.html
{% extends 'base.html' %}

{% block content %}
    <p>
        <a href="{% url 'credits:transaction_list' %}">
            ← Back to transaction overview
        </a>
    </p>
    <h3>Transfer money</h3>
    <p>
        You can transfer money from your own balance to other users or an association.
        Your balance cannot become negative.
        You can use this to withdraw money from your account, to do this search a board member
        (preferably treasurer) from your association and ask for help.
    </p>
    <div class="alert alert-warning">
        A money transfer can only be undone by the receiving party!
        Check the fields carefully before creating a new transaction.
        To undo a transfer, ask the receiving party to create a new opposite transaction.
    </div>
    <form method="post">
        {% csrf_token %}
        {% include "snippets/bootstrap_form.html" with horizontal=True %}
        <input type="submit" value="Create transaction" class="btn btn-block btn-primary"/>
    </form>
{% endblock %}

assets/templates/credit_management/transaction_add_association.html
{% extends 'base.html' %}

{% block content %}
    <p>
        <a href="{% url 'association_credits' association_name=view.kwargs.association_name %}">
            ← Back to transaction overview
        </a>
    </p>
    <h3>Transfer money</h3>
    <p>
        As an association board member you can transfer money to user accounts or other associations.
        Use this to allow members of any association to deposit money in their account. The procedure for this is:
    </p>
    <ul>
        <li>An association member can ask you to deposit money in their account.</li>
        <li>You receive the money and store it in the cash box of your association (if it's cash), or hand it over to
            the treasurer.
        </li>
        <li>You transfer the money to their account using this page.</li>
    </ul>
    <p>
        The money remains theirs which is why the association balance decreases by the transfer amount!
        At any moment your association can repay the money received from users to Scala to correct the negative balance
        of your association.
        Whenever the user pays for kitchen cost, the amount is transferred to a special kitchen cost account,
        Scala uses this account for the kitchen payment.
    </p>
    <p></p>
    <div class="alert alert-warning">
        A money transfer can only be undone by the receiving party!
        Check the fields carefully before creating a new transaction.
    </div>
    <form method="post">
        {% csrf_token %}
        {% include "snippets/bootstrap_form.html" with horizontal=True %}
        <input type="submit" value="Create transaction" class="btn btn-block btn-primary"/>
    </form>
{% endblock %}

assets/templates/credit_management/transaction_delete.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h3>Detele transaction</h3>
        <form method="post">
            {% csrf_token %}
            <p>
                Are you sure you want to undo the following transaction?
            </p>
            <p class="py-4">{{ transaction_text }}</p>

            <div class="row mt-3">
                <div class="col-6">
                    <a class="btn btn-secondary btn-block"
                       href="{{ redirect }}">
                        No, go back
                    </a>
                </div>
                <div class="col-6">
                    <input type="submit" value="Yes, delete it" class="btn btn-block btn-danger"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

assets/templates/credit_management/transaction_edit.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h3>Change transaction</h3>
        <form method="post">
            {% csrf_token %}
            {% include "snippets/bootstrap_form.html" with horizontal=True %}

            <div class="row">
                <div class="col-md-4 mt-1">
                    <a class="btn btn-secondary btn-block"
                       href="{{ redirect }}">
                        Cancel
                    </a>
                </div>
                <div class="col-md-6 mt-1">
                    <input type="submit" value="Save" class="btn btn-block btn-primary"/>
                </div>
                <div class="col-md-2 mt-1">
                    <a class="btn btn-danger btn-block"
                       href="{% url 'credits:transaction_delete' %}?redirect={{ redirect }}&id={{ form.instance.pk }}">
                        Delete
                    </a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

assets/templates/credit_management/transaction_history.html
{% extends 'base.html' %}

{% block title %}Transaction history - {{ block.super }}{% endblock %}

{% block content %}
    <h2>Transaction history</h2>
    <p>
        <a href="{% url 'credits:transaction_add' %}" class="btn btn-primary">
            <i class="fas fa-plus"></i> Money transfer
        </a>
        <a href="{% url 'credits:transaction_csv' pk=user.account.pk %}" class="btn btn-secondary">
            <i class="fas fa-file-export"></i> Download CSV
        </a>
    </p>
    {% include 'credit_management/transaction_table.html' with account_self=user.account hide_created_by=True %}

    {% include 'snippets/paginator.html' %}

{% endblock %}

assets/templates/credit_management/transaction_table.html
{% load credit_tags %}
<div class="table-responsive">
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Other party</th>
            <th scope="col">Amount</th>
            <th scope="col">Description</th>
            {% if not hide_created_by %}<th scope="col">Created by</th>{% endif %}
        </tr>
        </thead>
        <tbody>
        {% for tx in object_list %}
            <tr>
                <td>{{ tx.moment|date:"SHORT_DATE_FORMAT" }}</td>
                <td>
                    {% if tx.source == account_self %}
                        {{ tx.target }}
                    {% else %}
                        {{ tx.source }}
                    {% endif %}
                </td>
                <td>
                    {% if tx.source == account_self %}
                        <span class="text-danger">-{{ tx.amount|euro }}</span>
                    {% else %}
                        <span class="text-success">+{{ tx.amount|euro }}</span>
                    {% endif %}
                </td>
                <td>{{ tx.description }}</td>
                {% if not hide_created_by %}<td>{{ tx.created_by }}</td>{% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>