Dining/urls.py
from django.urls import include, path

from . import views
from .views import DayView, index

urlpatterns = [
    path('', index, name='index'),
    path('csv/', views.DailyDinersCSVView.as_view(), name="diners_csv"),
    path('<int:day>/<int:month>/<int:year>/', include([
        path('', DayView.as_view(), name='day_view'),
        path('add/', views.NewSlotView.as_view(), name='new_slot'),
        path('<slug:identifier>/', include([
            path('', views.SlotInfoView.as_view(), name='slot_details'),
            path('list/', views.SlotListView.as_view(), name='slot_list'),
            path('allergy/', views.SlotAllergyView.as_view(), name='slot_allergy'),
            path('entry/add/', views.EntryAddView.as_view(), name='entry_add'),
            path('change/', views.SlotInfoChangeView.as_view(), name='slot_change'),
            path('delete/', views.SlotDeleteView.as_view(), name='slot_delete'),
            path('inform_payment/', views.SlotPaymentView.as_view(), name='slot_inform_payment'),
        ])),
    ])),
    path('entries/<int:pk>/delete/', views.EntryDeleteView.as_view(), name='entry_delete'),
]

reports/urls.py
from django.urls import path

from reports import views

app_name = "reports"

urlpatterns = [
    path("", views.ReportsView.as_view(), name="index"),
    path("balance/", views.BalanceView.as_view(), name="balance"),
    path("cashflow/", views.CashFlowIndexView.as_view(), name="cashflow_index"),
    path("cashflow/<int:pk>/", views.CashFlowView.as_view(), name="cashflow"),
    path("cashflow2/", views.CashFlowMatrixView.as_view(), name="cashflow_matrix"),
    path("transactions/", views.TransactionsReportView.as_view(), name="transactions"),
    path("stale/", views.StaleAccountsView.as_view(), name="stale"),
    path("memberships/", views.MembershipCountView.as_view(), name="memberships"),
    path("diners/", views.DinersView.as_view(), name="diners"),
    path("leaderboard/", views.LeaderboardView.as_view(), name="leaderboard"),
]

scaladining/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("credit/", include("creditmanagement.urls")),
    path("site/", include("general.urls")),
    path("reports/", include("reports.urls")),
    path("", include("dining.urls")),
    path("accounts/", include("userdetails.urls")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/views.py
from decimal import Decimal
from urllib.parse import urlencode

from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import BadRequest
from django.db.models import Case, Count, Q, Sum, When
from django.utils.timezone import localdate, now
from django.views.generic import DetailView, TemplateView

from creditmanagement.models import Account, Transaction
from reports import queries
from reports.period import Period
from userdetails.models import Association, UserMembership


class ReportAccessMixin(UserPassesTestMixin):
    def test_func(self):
        return (
            self.request.user.is_authenticated
            and self.request.user.has_site_stats_access()
        )


class ReportsView(ReportAccessMixin, TemplateView):
    template_name = "reports/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "association_accounts": Account.objects.filter(
                    association__isnull=False
                ).order_by("association__name"),
                "bookkeeping_accounts": Account.objects.filter(special__isnull=False),
            }
        )
        return context


class PeriodMixin:
    """Mixin for yearly reporting periods.

    Attributes:
        view_choice: Boolean that enables or disables choosing a different view.
    """

    default_view = "yearly"
    view_choice = True

    def get_period(self) -> Period:
        view = self.request.GET.get("view", self.default_view)

        # When view_choice is False we can only use the default view
        if not self.view_choice and view != self.default_view:
            raise BadRequest

        try:
            period_class = Period.get_class(view)

            if "period" in self.request.GET:
                return period_class.from_url_param(self.request.GET["period"])
            else:
                return period_class.from_datetime(now())
        except ValueError:
            raise BadRequest

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Save the query strings to the context for use in template URLs.
        query = urlencode(
            [(k, v) for k, v in self.request.GET.items() if k not in ("period", "view")]
        )
        context.update(
            {
                "view_choice": self.view_choice,
                "additional_query": f"&{query}" if query else "",
            }
        )
        if self.period:
            context["period"] = self.period
        return context

    def get(self, request, *args, **kwargs):
        # Add period to this instance
        self.period = self.get_period()
        return super().get(request, *args, **kwargs)


class BalanceView(ReportAccessMixin, PeriodMixin, TemplateView):
    """Periodical reports of the balance of all credit accounts.

    User accounts are aggregated as one large pile. Association and bookkeeping
    accounts are shown individually.
    """

    template_name = "reports/balance.html"

    def get_report(self):
        """Computes the balance statements."""
        if self.period.start() > now():
            # If the start of period is in the future, we cannot compute the start
            # balance and there are no statements.
            return {}

        # All transactions before current period
        before_tx = Transaction.objects.filter(moment__lt=self.period.start())
        # All transactions in this period
        period_tx = self.period.get_transactions()

        # Compute opening balance from all transaction before the current period
        opening = before_tx.sum_by_account(group_users=True)  # type: dict
        # Compute increase and reduction sum in this period
        mutation = period_tx.sum_by_account(group_users=True)  # type: dict

        # Add opening balances to report
        statements = {
            account: {"start_balance": increase - reduction}
            for account, (increase, reduction) in opening.items()
        }

        # Add mutations to report
        for account, (increase, reduction) in mutation.items():
            statement = statements.setdefault(account, {"start_balance": None})
            start = statement["start_balance"] or Decimal("0.00")
            statement.update(
                {
                    "increase": increase,
                    "reduction": reduction,
                    "end_balance": start + increase - reduction,
                }
            )

        return statements

    def get_context_data(self, **kwargs):
        # This function just regroups and sorts the values for display
        context = super().get_context_data(**kwargs)

        # The accounts to display in the report
        accounts = list(
            Account.objects.exclude(user__isnull=False).order_by(
                "special", "association__short_name"
            )
        )
        accounts.append(None)  # User pile

        # Add statements to context
        statements = self.get_report()
        context["rows"] = [
            (account, statements.get(getattr(account, "pk", None), {}))
            for account in accounts
        ]
        return context


class CashFlowView(ReportAccessMixin, PeriodMixin, DetailView):
    """Periodical reports of money entering and leaving a specific account.

    For a selected account, shows the flow of money to and from other accounts
    in a certain period.
    """

    template_name = "reports/cashflow.html"
    model = Account
    context_object_name = "account"

    def get_statements(self):
        """Returns a dictionary from Account or None to an income/outgoings tuple."""
        tx = self.period.get_transactions()
        # Aggregate income and outgoings
        income = (
            tx.filter(target=self.object)
            # Set the group key to NULL for all user accounts
            .annotate(
                account=Case(
                    When(source__user__isnull=False, then=None),
                    default="source",
                )
            )
            # Group by source account
            .values("account")
            # Sum amount for each separate source
            .annotate(sum=Sum("amount"))
        )
        outgoings = (
            # See above for income
            tx.filter(source=self.object)
            .annotate(
                account=Case(
                    When(target__user__isnull=False, then=None),
                    default="target",
                )
            )
            .values("account")
            .annotate(sum=Sum("amount"))
        )

        # Regroup on account
        income = {v["account"]: v["sum"] for v in income}
        outgoings = {v["account"]: v["sum"] for v in outgoings}
        regroup = {
            # Retrieve Account from db
            Account.objects.get(pk=account) if account else None: (
                income.get(account),
                outgoings.get(account),
            )
            for account in income.keys() | outgoings.keys()
        }
        return regroup

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Convert to list of tuples
        statements = [
            (account, inc, out) for account, (inc, out) in self.get_statements().items()
        ]
        # Sort in 3 steps to have first the bookkeeping accounts in
        # alphabetical order, then the association accounts in order and
        # then the user pile.
        #
        # This works because sort is stable.
        statements.sort(
            key=lambda v: v[0].association.name if v[0] and v[0].association else ""
        )
        statements.sort(key=lambda v: v[0].special if v[0] and v[0].special else "")
        statements.sort(
            key=lambda v: 2 if v[0] is None else 1 if v[0].association else 0
        )

        context["statements"] = statements
        return context


class CashFlowIndexView(ReportAccessMixin, TemplateView):
    template_name = "reports/cashflow_index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "association_accounts": Account.objects.filter(
                    association__isnull=False
                ).order_by("association__name"),
                "bookkeeping_accounts": Account.objects.filter(special__isnull=False),
            }
        )
        return context


class TransactionsReportView(ReportAccessMixin, PeriodMixin, TemplateView):
    """Report to view all transactions excluding those involving user accounts."""

    template_name = "reports/transactions.html"
    default_view = "yearly"
    view_choice = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "transactions": self.period.get_transactions()
                .filter(
                    source__user__isnull=True,
                    target__user__isnull=True,
                )
                .order_by("moment")
            }
        )
        return context


class CashFlowMatrixView(ReportAccessMixin, PeriodMixin, TemplateView):
    template_name = "reports/cashflow_matrix.html"

    def get_matrix(self):
        """Computes the cash flow matrix and returns a two-dimensional dictionary."""
        tx = self.period.get_transactions()

        # Group by source/target combinations and sum the amount
        qs = (
            # Set the group key to NULL for all user accounts
            tx.annotate(
                source_key=Case(
                    When(source__user__isnull=False, then=None),
                    default="source",
                ),
                target_key=Case(
                    When(target__user__isnull=False, then=None),
                    default="target",
                ),
            )

assets/templates/reports/balance.html
{% extends 'reports/base.html' %}

{% block report %}
    <h2>Balance report <small class="text-muted">{{ period }}</small></h2>

    {% url 'reports:balance' as url %}{% include 'reports/snippets/controls.html' %}

    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Account</th>
            <th scope="col" class="text-right">Start balance</th>
            <th scope="col" class="text-right">Increase</th>
            <th scope="col" class="text-right">Reduction</th>
            <th scope="col" class="text-right">End balance</th>
        </tr>
        </thead>
        <tbody>
        {% for account, statement in rows %}
            <tr class="{% if account.special %}table-primary{% elif account.association %}table-secondary{% else %}table-dark{% endif %}">
                <td>
                    {% if account.special %}
                        {{ account.get_special_display }}
                    {% elif account.association %}
                        {{ account.association.get_short_name }}
                    {% else %}
                        User accounts<br>
                        <small class="text-muted">Sum of the balances of all user accounts.</small>
                    {% endif %}
                </td>
                <td class="text-right">{{ statement.start_balance|default_if_none:"" }}</td>
                <td class="text-right">{{ statement.increase|default_if_none:"" }}</td>
                <td class="text-right">{{ statement.reduction|default_if_none:"" }}</td>
                <td class="text-right">{{ statement.end_balance|default_if_none:"" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

assets/templates/reports/base.html
{% extends 'base.html' %}

{% block content %}
    {% block nav %}<a href="{% url 'reports:index' %}">← View all reports</a>{% endblock %}
    {% block report %}{% endblock %}
{% endblock %}

assets/templates/reports/cashflow.html
{% extends 'reports/base.html' %}

{% block nav %}
    <a href="{% url 'reports:cashflow_index' %}">← Choose account</a>
{% endblock %}

{% block report %}
    <h2>
        Cash flow
        <small class="text-muted">{{ account }} / {{ period }}</small>
    </h2>

    {% url 'reports:cashflow' pk=account.pk as url %}{% include 'reports/snippets/controls.html' %}

    <p class="lead">
        Inflow is in the direction from the opposite account towards
        the <strong>{{ account }}</strong> account. Outflow is in the other direction.
    </p>

    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Opposite account</th>
            <th scope="col" class="text-right w-25">Inflow</th>
            <th scope="col" class="text-right w-25">Outflow</th>
        </tr>
        </thead>
        <tbody>
        {% for account, inflow, outflow in statements %}
            <tr class="{% if account.special %}table-primary{% elif account.association %}table-secondary{% else %}table-dark{% endif %}">
                <td>
                    {% if account %}{{ account }}
                        <a href="{% url 'reports:cashflow' pk=account.pk %}?view={{ period.view_name }}&period={{ period.url_param }}">»</a>
                    {% else %}User accounts
                    {% endif %}
                </td>
                <td class="text-right">{{ inflow|default:"–" }}</td>
                <td class="text-right">{{ outflow|default:"–" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

assets/templates/reports/cashflow_index.html
{% extends 'reports/base.html' %}

{% block report %}
    <h2>Cash flow <small class="text-muted">Choose account</small></h2>
    <h4 class="mt-3">Bookkeeping accounts</h4>
    <div class="row">
        <div class="col-md-6">
            <div class="list-group">
                {% for account in bookkeeping_accounts %}
                <a href="{% url 'reports:cashflow' pk=account.pk %}"
                   class="list-group-item list-group-item-action">
                    {{ account }}
                </a>
                {% endfor %}
            </div>
        </div>
    </div>

    <h4 class="mt-3">Association accounts</h4>
    <div class="row">
        <div class="col-md-6">
            <div class="list-group">
                {% for account in association_accounts %}
                <a href="{% url 'reports:cashflow' pk=account.pk %}"
                   class="list-group-item list-group-item-action">
                    {{ account }}
                </a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

assets/templates/reports/cashflow_matrix.html
{% extends 'reports/base.html' %}

{% block report %}
    <h2>
        Cash flow matrix
        <small class="text-muted">{{ period }}</small>
    </h2>

    {% url 'reports:cashflow_matrix' as url %}{% include 'reports/snippets/controls.html' %}

    <div class="table-responsive">
        <table class="table table-sm">
            <thead>
            <tr>
                <td colspan="2" class="border-0"></td>
                <th colspan="{{ accounts|length }}" class="text-center">To</th>
            </tr>
            <tr>
                <td colspan="2" class="border-0"></td>
                {% for account in accounts %}
                    <th scope="col"
                        style="width: 4.5rem;"
                        class="text-center {% if account.special %}table-primary{% elif account.association %}
                            table-secondary{% else %}table-dark{% endif %}">
                        {% if account.special %}
                            {{ account.get_special_display|truncatechars:6 }}
                        {% elif account.association %}
                            {{ account.association.get_short_name|truncatechars:6 }}
                        {% else %}
                            Users
                        {% endif %}
                    </th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for account_from, row in table %}
                <tr>
                    {% if forloop.first %}
                        <th scope="row"
                            class="align-middle"
                            rowspan="{{ accounts|length }}">From
                        </th>
                    {% endif %}
                    <th scope="row"
                        class="{% if account_from.special %}bg-primary{% elif account_from.association %}bg-secondary{% else %}bg-dark{% endif %}">
                        {% if account_from.special %}
                            {{ account_from.get_special_display }}
                        {% elif account_from.association %}
                            {{ account_from.association.get_short_name }}
                        {% else %}
                            Users
                        {% endif %}
                    </th>
                    {% for account_to, amount in row %}
                        {% if account_from == account_to %}
                            <td class="text-center">×</td>
                        {% else %}
                            <td class="text-right">{{ amount|default:"" }}</td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

assets/templates/reports/diners.html
{% extends 'reports/base.html' %}

{% block report %}
    <h2>Diners report <small class="text-muted">{{ period }}</small></h2>
    {% url 'reports:diners' as url %}
    {% include 'reports/snippets/controls.html' %}

    <div class="table-responsive">
        <table class="table table-sm">
            <thead>
            <tr>
                <td colspan="2" class="border-0"></td>
                <th scope="col" colspan="4" class="text-center bg-secondary">Cooked for</th>
                <th scope="col" colspan="4" class="text-center">Kitchen usage<sup>1</sup></th>

            </tr>
            <tr>
                <th scope="col">Association</th>
                <th scope="col" class="text-right">Lists</th>
                <th scope="col" class="text-right bg-secondary">Total</th>
                <th scope="col" class="text-right bg-secondary">Own members</th>
                <th scope="col" class="text-right bg-secondary">Other members</th>
                <th scope="col" class="text-right bg-secondary">Guests</th>
                <th scope="col" class="text-center" colspan="2">Not weighted</th>
                <th scope="col" class="text-center" colspan="2">Weighted</th>
            </tr>
            </thead>
            <tbody>
            {% for association, metrics in report %}
                <tr class="{% if association is None %}table-secondary{% endif %}">
                    <th scope="row">
                        {% if association is None %}<em>Totals</em>
                        {% else %}{{ association.get_short_name }}{% endif %}
                    </th>
                    <td class="text-right">{{ metrics.dining_list_count }}</td>
                    <td class="text-right">{{ metrics.total_diners }}</td>
                    <td class="text-right">{{ metrics.association_diners }}</td>
                    <td class="text-right">{{ metrics.outside_diners }}</td>
                    <td class="text-right">{{ metrics.guests }}</td>
                    <td class="text-right">
                        {{ metrics.not_weighted_usage }}
                    </td>
                    <td class="text-left">
                        {% if metrics.not_weighted_percentage %}{{ metrics.not_weighted_percentage }}%{% endif %}
                    </td>
                    <td class="text-right">
                        {{ metrics.weighted_usage }}
                    </td>
                    <td class="text-left">
                        {% if metrics.weighted_percentage %}{{ metrics.weighted_percentage }}%{% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <h4>Settings</h4>
    <div class="row mb-3">
        <div class="col-sm-2">
            <strong>Memberships</strong>
        </div>
        <div class="col-sm-10">
            <div class="btn-group btn-group-sm">
                {# @formatter:off #}
                <a href="{{ url }}?view={{ period.view_name }}&period={{ period.url_param }}{% if request.GET.include_guests %}&include_guests=on{% endif %}"
                {# @formatter:on #}
                   class="btn btn-secondary {% if not request.GET.all_members %}disabled{% endif %}">
                    {% if not request.GET.all_members %}<i class="fas fa-check"></i>{% endif %}
                    Verified only
                </a>
                {# @formatter:off #}
                <a href="{{ url }}?view={{ period.view_name }}&period={{ period.url_param }}&all_members=on{% if request.GET.include_guests %}&include_guests=on{% endif %}"
                {# @formatter:on #}
                   class="btn btn-secondary {% if request.GET.all_members %}disabled{% endif %}">
                    {% if request.GET.all_members %}<i class="fas fa-check"></i>{% endif %}
                    Verified, rejected and pending
                </a>
            </div>
            <small class="text-muted d-block mt-1">
                This affects all columns that use memberships, in particular kitchen usage, individuals and owners.
                When selecting 'verified only', note that some associations change the membership to rejected
                when a diner left an association. These diners are not included in the count even though they were
                likely
                a verified member at the time!
            </small>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-sm-2">
            <strong>Guests</strong>
        </div>
        <div class="col-sm-10">
            <div class="btn-group btn-group-sm">
                {# @formatter:off #}
                <a href="{{ url }}?view={{ period.view_name }}&period={{ period.url_param }}{% if request.GET.all_members %}&all_members=on{% endif %}"
                {# @formatter:on #}
                   class="btn btn-secondary {% if not request.GET.include_guests %}disabled{% endif %}">
                    {% if not request.GET.include_guests %}<i class="fas fa-check"></i>{% endif %}
                    Not included
                </a>
                {# @formatter:off #}
                <a href="{{ url }}?view={{ period.view_name }}&period={{ period.url_param }}&include_guests=on{% if request.GET.all_members %}&all_members=on{% endif %}"
                {# @formatter:on #}
                   class="btn btn-secondary {% if request.GET.include_guests %}disabled{% endif %}">
                    {% if request.GET.include_guests %}<i class="fas fa-check"></i>{% endif %}
                    Included
                </a>
            </div>
            <small class="text-muted d-block mt-1">
                Whether to include guests when calculating the kitchen usage.
                A guest counts towards the association(s) of the diner who added the guest.
            </small>

        </div>
    </div>

    {# The purpose of this grid is to make the lines not too long for readability. #}
    <div class="row">
        <div class="col-md-8">

            <h4><sup>1</sup>Kitchen usage</h4>
            <p>
                The kitchen usage counts the
                number of times a member of the association joined a dining list.
                In the <strong>weighted</strong> column, members who are a member of
                two or more associations are only counted for 1/(number of associations) instead
                of once for each association.
            </p>
            <p>
                Example: Roan is a member of the Knights and Q and joined 2 lists.
                Anne is a member of only Q and also joined 2 lists.
                The kitchen usage for Knights/Q in the non-weighted case is 4/2 (67%/33%).
                In the weighted case it is 3/2 (60%/40%)
            </p>
        </div>
        {#        <div class="col-md-6"></div>#}
        {#        <div class="col-md-8">#}
        {#            <h4><sup>2</sup>Joiners and owners</h4>#}
        {#            <p>#}
        {#                The joiner and owner counts are the number of members of the association#}
        {#                who respectively joined or owned a dining list in the current period at least once.#}
        {#                The percentage is taken over the total number of members in the association.#}
        {#            </p>#}
        {#        </div>#}
    </div>
{% endblock %}

assets/templates/reports/index.html
{% extends 'reports/base.html' %}

{% block content %}
    <h2>Reports</h2>

    <div class="row">
        <div class="col-md-6">
            <h4>Finance</h4>

            <div class="list-group">
                <a href="{% url 'reports:balance' %}" class="list-group-item list-group-item-action">
                    Balance
                </a>
                <a href="{% url 'reports:cashflow_matrix' %}" class="list-group-item list-group-item-action">
                    Cash flow matrix
                </a>
                <a href="{% url 'reports:transactions' %}" class="list-group-item list-group-item-action">
                    Site transactions
                </a>
                <a href="{% url 'reports:stale' %}" class="list-group-item list-group-item-action">
                    Stale accounts
                </a>
            </div>
            <div class="list-group mt-3">
                <a href="{% url 'reports:cashflow_index' %}" class="list-group-item list-group-item-action">
                    Cash flow<br>
                    <small class="text-muted">
                        Deprecated: this report has been superseded by the cash flow matrix which
                        provides the same info. This report will be removed.
                    </small>
                </a>
            </div>
        </div>

        <div class="col-md-6">
            <h4>Dining</h4>
            <div class="list-group">
                <a href="{% url 'reports:diners' %}" class="list-group-item list-group-item-action">
                    Diners
                </a>
                <a href="{% url 'reports:memberships' %}" class="list-group-item list-group-item-action">
                    Membership counts
                </a>
                <a href="{% url 'reports:leaderboard' %}" class="list-group-item list-group-item-action">
                    Leaderboard
                </a>
            </div>
        </div>
    </div>
{% endblock %}

assets/templates/reports/transactions.html
{% extends 'reports/base.html' %}

{% block report %}
    <h2>Site transactions <small class="text-muted">{{ period }}</small></h2>

    {% url 'reports:transactions' as url %}{% include 'reports/snippets/controls.html' %}

    <p class="lead">
        Site transactions between any association or bookkeeping account, <em>excluding</em>
        transactions to or from any user account.
        These excluded transactions are usually deposits, withdrawals or kitchen payments.
    </p>
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Date (dd-mm)</th>
            <th scope="col">Source</th>
            <th scope="col">Destination</th>
            <th scope="col" class="text-right">Amount</th>
            <th scope="col">Description</th>
            <th scope="col">Created by</th>
        </tr>
        </thead>
        <tbody>
        {% for tx in transactions %}
            <tr>
                <td>{{ tx.moment|date:"d-m" }}</td>
                <td class="{% if tx.source.special %}bg-primary{% endif %}">
                    {% if tx.source.association %}{{ tx.source.association.get_short_name }}
                    {% else %}{{ tx.source }}{% endif %}
                </td>
                <td class="{% if tx.target.special %}bg-primary{% endif %}">
                    {% if tx.target.association %}{{ tx.target.association.get_short_name }}
                    {% else %}{{ tx.target }}{% endif %}
                </td>
                <td class="text-right">{{ tx.amount }}</td>
                <td>{{ tx.description }}</td>
                <td>{{ tx.created_by }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}