CreditManagement/urls.py
from django.urls import path

from CreditManagement.views import MoneyObtainmentView, TransactionAddView, TransactionFinalisationView, \
    TransactionListView

app_name = 'credits'

urlpatterns = [
    path('transactions/', TransactionListView.as_view(), name='transaction_list'),
    path('transactions/add', TransactionAddView.as_view(), name='transaction_add'),
    path('finalise_transactions/', TransactionFinalisationView.as_view(), name='transactions_finalise'),
    path('dining_money/', MoneyObtainmentView.as_view(), name='dining_money')
]

Dining/urls.py
from django.urls import include, path

from . import views
from .views import DayView, index

urlpatterns = [
    path('', index, name='index'),
    path('csv/', views.DailyDinersCSVView.as_view(), name="diners_csv"),
    path('<int:day>/<int:month>/<int:year>/', include([
        path('', DayView.as_view(), name='day_view'),
        path('add/', views.NewSlotView.as_view(), name='new_slot'),
        path('<slug:identifier>/', include([
            path('', views.SlotInfoView.as_view(), name='slot_details'),
            path('list/', views.SlotListView.as_view(), name='slot_list'),
            path('allergy/', views.SlotAllergyView.as_view(), name='slot_allergy'),
            path('entry/add/', views.EntryAddView.as_view(), name='entry_add'),
            path('change/', views.SlotInfoChangeView.as_view(), name='slot_change'),
            path('delete/', views.SlotDeleteView.as_view(), name='slot_delete'),
            path('inform_payment/', views.SlotPaymentView.as_view(), name='slot_inform_payment'),
        ])),
    ])),
    path('entries/<int:pk>/delete/', views.EntryDeleteView.as_view(), name='entry_delete'),
]

reports/urls.py
from django.urls import path

from reports import views

app_name = "reports"

urlpatterns = [
    path("", views.ReportsView.as_view(), name="index"),
    path("balance/", views.BalanceView.as_view(), name="balance"),
    path("cashflow/", views.CashFlowIndexView.as_view(), name="cashflow_index"),
    path("cashflow/<int:pk>/", views.CashFlowView.as_view(), name="cashflow"),
    path("cashflow2/", views.CashFlowMatrixView.as_view(), name="cashflow_matrix"),
    path("transactions/", views.TransactionsReportView.as_view(), name="transactions"),
    path("stale/", views.StaleAccountsView.as_view(), name="stale"),
    path("memberships/", views.MembershipCountView.as_view(), name="memberships"),
    path("diners/", views.DinersView.as_view(), name="diners"),
    path("leaderboard/", views.LeaderboardView.as_view(), name="leaderboard"),
]

scaladining/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("credit/", include("creditmanagement.urls")),
    path("site/", include("general.urls")),
    path("reports/", include("reports.urls")),
    path("", include("dining.urls")),
    path("accounts/", include("userdetails.urls")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assets/templates/base.html
{% extends 'base_no_navbar.html' %}
{% load credit_tags %}
{% load static %}

{% block body %}
    <nav class="navbar navbar-expand navbar-dark bg-primary">
        <a href="{% url 'index' %}" class="navbar-brand mr-auto">
            <img src="{% static "images/Scala_dining.png" %}" height="40" alt="Scala Dining">
            <span class="h3 d-none d-lg-inline"
                  style="line-height: 40px; vertical-align: middle; margin: 0 0 0 10px"> Scala Dining</span>
            <span class="h5 d-none d-md-inline d-lg-none"
                  style="line-height: 40px; vertical-align: middle; margin: 0 0 0 10px"> Scala Dining</span>
        </a>
        {% with justify="d-flex justify-content-between align-items-center" %}
            {% if user.is_authenticated %}
                <span class="navbar-text small text-right px-2">
                    {{ user }}<br>
                    {{ user.account.balance|euro }}
                </span>
                <div class="navbar-nav">
                    <div class="nav-item dropdown">
                        {# (mb-0 is needed to cancel the margin that gets added by h4) #}
                        <a class="nav-link dropdown-toggle h4 mb-0" href="#" data-toggle="dropdown">
                            <i class="fas fa-user"></i>
                            {% if user.requires_action %}
                                <span style="position: relative;">
                                    <span class="badge badge-pill badge-warning"
                                          style="font-size: x-small; position: absolute; top: -5px; left: -8px">!</span>
                                </span>
                            {% endif %}
                        </a>
                        {# A slightly larger min-width to add space between the text and icons #}
                        <div class="dropdown-menu dropdown-menu-right" style="min-width: 10.5rem;">
                            <a class="dropdown-item {{ justify }}" href="{% url 'history_lists' %}">
                                History <i class="fas fa-history fa-fw"></i>
                            </a>
                            <a class="dropdown-item {{ justify }}" href="{% url 'credits:transaction_list' %}">
                                Transactions <i class="fas fa-euro-sign fa-fw"></i>
                            </a>
                            <a class="dropdown-item {{ justify }}" href="{% url 'settings_account' %}">
                                Settings <i class="fas fa-cog fa-fw"></i>
                            </a>
                            {% if user.boards.count > 0 %}
                                <div class="dropdown-divider"></div>
                            {% endif %}
                            {% for association in user.boards %}
                                <a class="dropdown-item {{ justify }}"
                                   href="{% url 'association_overview' slug=association.slug %}">
                                    <span>
                                        {{ association.get_short_name }}
                                        {% if association.requires_action %}
                                            <span class="badge badge-pill badge-warning">!</span>
                                        {% endif %}
                                    </span>
                                    {% if association.image %}
                                        <i class="fas fa-fw">
                                            <img src="{{ association.image.url }}" class="w-100">
                                        </i>
                                    {% endif %}
                                </a>
                            {% endfor %}
                            {% if user.has_site_stats_access or user.has_admin_site_access %}
                                <div class="dropdown-divider"></div>
                            {% endif %}
                            {% if user.has_site_stats_access %}
                                <a class="dropdown-item {{ justify }}" href="{% url 'reports:index' %}">
                                    Reports <i class="fas fa-chart-line fa-fw"></i>
                                </a>
                            {% endif %}
                            {% if user.has_admin_site_access %}
                                <a class="dropdown-item {{ justify }}" href="{% url 'admin:index' %}">
                                    Control panel <i class="fas fa-toolbox fa-fw"></i>
                                </a>
                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <form method="post" action="{% url 'account_logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item {{ justify }}">
                                    Log out <i class="fas fa-power-off fa-fw"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        {# (mb-0 is needed to cancel the margin that gets added by h4) #}
                        <a class="nav-link dropdown-toggle h4 mb-0" href="#" data-toggle="dropdown">
                            <i class="fas fa-info"></i>
                            {% if user.requires_information_rules or user.requires_information_updates %}
                                <span style="position: relative;">
                                    <span class="badge badge-pill badge-warning"
                                          style="font-size: x-small; position: absolute; top: -5px; left: -6px">!</span>
                                </span>
                            {% endif %}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item {{ justify }}" href="{% url 'help_page' %}">
                                Help <i class="fas fa-question"></i>
                            </a>
                            <a class="dropdown-item" href="{% url 'upgrade_instructions' %}">
                                Upgrading balance
                            </a>
                            <a class="dropdown-item" href="{% url 'rules_and_regulations' %}">
                                Rules & regulation
                                {% if user.requires_information_rules %}
                                    <span class="badge badge-pill badge-warning">!</span>
                                {% endif %}
                            </a>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="navbar-nav">
                    <div class="nav-item text-right px-2">
                        <a class="nav-link" href="{% url 'account_login' %}?next={{ request.get_full_path }}">Log in</a>
                    </div>
                    <div class="nav-item dropdown">
                        {# (mb-0 is needed to cancel the margin that gets added by h4) #}
                        <a class="nav-link dropdown-toggle h4 mb-0" href="#" data-toggle="dropdown">
                            <i class="fas fa-info"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item {{ justify }}" href="{% url 'help_page' %}">
                                Help <i class="fas fa-question"></i>
                            </a>
                            <a class="dropdown-item" href="{% url 'upgrade_instructions' %}">
                                Upgrading balance
                            </a>
                            <a class="dropdown-item" href="{% url 'rules_and_regulations' %}">
                                Rules & regulation
                            </a>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endwith %}
    </nav>

    <div class="container mt-3 mb-5">
{#        {% if user.allergies and request.path != '/accounts/settings/' %}#}
        {% if user.allergies %}
            <div class="alert alert-info">
                <p>
                    <i class="fas fa-exclamation-circle"></i>
                    Food preferences and allergies are now separate fields.
                    Please re-enter any preference or allergy in your user profile.
                </p>
                <a href="{% url 'settings_account' %}#allergies"
                   class="stretched-link btn btn-primary text-decoration-none">
                    To user profile
                </a>
            </div>
        {% endif %}

        {# Banner for invalid e-mails #}
        {% if user.has_invalid_email %}
            <div class="alert alert-warning">
                <p>
                    <i class="fas fa-exclamation-triangle"></i>
                    It seems that your e-mail address does not work anymore.
                    Please update your profile by adding a new e-mail address and making it primary.
                    If your e-mail address is correct and this notice is in error, please let us know via
                    <a href="mailto:diningapp@studentencultuur.nl">diningapp@studentencultuur.nl</a>.
                </p>
                <a href="{% url 'account_email' %}" class="stretched-link btn btn-secondary text-decoration-none">
                    Update e-mail
                </a>
            </div>
        {% endif %}

        {% include 'snippets/negative_balance_alert.html' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible"
                     role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
    </div>
{% endblock %}

assets/templates/base_no_navbar.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {# Vendor CSS #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.6.2/dist/darkly/bootstrap.min.css"
          integrity="sha256-Z4AEnSs0JXuM2TJuvLaXcZDmkIoZ6r4T0cgNEkETs6c=" crossorigin="anonymous">
    {# See https://fontawesome.com/docs/web/use-with/python-django #}
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

    {# Own CSS customizations #}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block head %}{% endblock %}
    <title>{% block title %}Scala Dining{% endblock %}</title>
    {# Favicon icons from RealFaviconGenerator.net #}
    {% include "icons.html" %}
    {# django-autocomplete-light needs jQuery loaded for its Select2 widget therefore I put jQuery in head #}
    <script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
</head>
<body>
{% if SITE_BANNER %}
    <div class="w-100 bg-warning text-center p-1">{{ SITE_BANNER }}</div>
{% endif %}
{% block body %}{% endblock %}
{# Bootstrap JS bundle (jQuery is already loaded in the head). #}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
<script src="{% static 'dining.js' %}"></script>
{% if debug %}
    <script>console.log({{ sql_queries|safe }})</script>
{% endif %}
</body>
</html>

assets/templates/icons.html
{% load static %}
<link rel="apple-touch-icon" sizes="180x180" href="{% static "icons/apple-touch-icon.png" %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static "icons/favicon-32x32.png" %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static "icons/favicon-16x16.png" %}">
<link rel="manifest" href="{% static "icons/site.webmanifest" %}">
<link rel="mask-icon" href="{% static "icons/safari-pinned-tab.svg" %}" color="#375a7f">
<link rel="shortcut icon" href="{% static "icons/favicon.ico" %}">
<meta name="apple-mobile-web-app-title" content="Scala Dining">
<meta name="application-name" content="Scala Dining">
<meta name="msapplication-TileColor" content="#2b5797">
<meta name="msapplication-config" content="{% static "icons/browserconfig.xml" %}">
<meta name="theme-color" content="#375a7f">