CreditManagement/urls.py
from django.urls import path

from CreditManagement.views import MoneyObtainmentView, TransactionAddView, TransactionFinalisationView, \
    TransactionListView

app_name = 'credits'

urlpatterns = [
    path('transactions/', TransactionListView.as_view(), name='transaction_list'),
    path('transactions/add', TransactionAddView.as_view(), name='transaction_add'),
    path('finalise_transactions/', TransactionFinalisationView.as_view(), name='transactions_finalise'),
    path('dining_money/', MoneyObtainmentView.as_view(), name='dining_money')
]

Dining/urls.py
from django.urls import include, path

from . import views
from .views import DayView, index

urlpatterns = [
    path('', index, name='index'),
    path('csv/', views.DailyDinersCSVView.as_view(), name="diners_csv"),
    path('<int:day>/<int:month>/<int:year>/', include([
        path('', DayView.as_view(), name='day_view'),
        path('add/', views.NewSlotView.as_view(), name='new_slot'),
        path('<slug:identifier>/', include([
            path('', views.SlotInfoView.as_view(), name='slot_details'),
            path('list/', views.SlotListView.as_view(), name='slot_list'),
            path('allergy/', views.SlotAllergyView.as_view(), name='slot_allergy'),
            path('entry/add/', views.EntryAddView.as_view(), name='entry_add'),
            path('change/', views.SlotInfoChangeView.as_view(), name='slot_change'),
            path('delete/', views.SlotDeleteView.as_view(), name='slot_delete'),
            path('inform_payment/', views.SlotPaymentView.as_view(), name='slot_inform_payment'),
        ])),
    ])),
    path('entries/<int:pk>/delete/', views.EntryDeleteView.as_view(), name='entry_delete'),
]

groceries/urls.py
from django.urls import path

from groceries import views

app_name = 'groceries'
urlpatterns = [
    path('', views.PaymentsView.as_view(), name='overview'),
    path('create/<int:pk>/', views.PaymentCreateView.as_view(), name='payment-create'),
    path('<int:pk>/', views.PaymentDetailView.as_view(), name='payment-detail'),
    path('pay/<int:pk>/', views.PayView.as_view(), name='pay'),
]

scaladining/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("credit/", include("creditmanagement.urls")),
    path("site/", include("general.urls")),
    path("reports/", include("reports.urls")),
    path("", include("dining.urls")),
    path("accounts/", include("userdetails.urls")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groceries/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone

from creditmanagement.models import Transaction
from dining.models import DiningList
from userdetails.models import User


class Payment(models.Model):
    """A groceries payment, where 1 person receives the grocery costs from the other diners."""
    dining_list = models.ForeignKey(DiningList, on_delete=models.PROTECT)
    receiver = models.ForeignKey(User, on_delete=models.PROTECT)
    # Total groceries cost is not really necessary, but we'll store it anyway as a nice memory
    total_cost = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))])
    # Cost per person can be derived from total cost (not the other way around
    # because rounding took place). However let's store it separately anyway in
    # case we later want to change how cost_pp is derived from total cost.
    cost_pp = models.DecimalField('groceries cost per person',
                                  max_digits=8,
                                  decimal_places=2,
                                  validators=[MinValueValidator(Decimal('0.01'))])
    payment_link = models.URLField(
        blank=True,
        help_text="E.g. Tikkie or ING Payment Request.")
    remarks = models.CharField(max_length=200,
                               blank=True,
                               help_text="For instance an IBAN number if you can't provide a payment link.")
    allow_transaction = models.BooleanField(
        'enable payment to your account balance',
        default=True,
        help_text="If you only want to receive payments in cash, e.g. via the payment link, uncheck this.")

    created_at = models.DateTimeField(default=timezone.now)

    def paid(self):
        """Returns a QuerySet of paid entries."""
        return self.entries.filter(paid=True)


class PaymentEntry(models.Model):
    """A user entry who needs to pay for a payment.

    Note: we don't create an entry for the receiver, thus if a payment is for 6 diners, it has 5 entries.
    """
    payment = models.ForeignKey(Payment, on_delete=models.PROTECT, related_name='entries')
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    # Just like for dining list entries, external entries have to be reflected here as well
    external_name = models.CharField(max_length=100, blank=True)
    paid = models.BooleanField(default=False)
    transaction = models.ForeignKey(Transaction, on_delete=models.PROTECT, null=True)

    class Meta:
        ordering = ('external_name', 'user__first_name', 'user__last_name')

    def is_external(self):
        return bool(self.external_name)

    def is_internal(self):
        return not self.is_external()

groceries/forms.py
from decimal import Decimal, ROUND_UP

from django import forms
from django.core.exceptions import ValidationError
from django.db import transaction

from groceries.models import Payment


class PaymentCreateForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ('total_cost', 'payment_link', 'remarks', 'allow_transaction')

    def get_cost_per_person(self) -> Decimal:
        """Calculates cost per person using the total cost set on the Payment instance."""
        payment = self.instance  # type: Payment
        nr_diners = payment.dining_list.diners.count()
        cost_pp = payment.total_cost / nr_diners  # If nr_diners==0, this will raise exception
        # Round up to remove missing cents
        return cost_pp.quantize(Decimal('.01'), rounding=ROUND_UP)

    def clean(self):
        # Let's prevent creating a payment if there are no diners
        # (even though it shouldn't cause any issues).
        cleaned_data = super().clean()
        if self.instance.dining_list.diners.count() == 0:
            raise ValidationError("Can't create groceries payment when there are no diners.")
        return cleaned_data

    def save(self, commit=True):
        payment = super().save(commit=False)  # type: Payment
        payment.cost_pp = self.get_cost_per_person()

        if commit:
            with transaction.atomic():
                payment.save()
                # Create the payment entries from dining entries
                for entry in payment.dining_list.entries.all():
                    if entry.is_internal() and entry.user == payment.receiver:
                        # We do not create an entry for the receiver
                        continue
                    payment.entries.create(
                        user=entry.user,
                        external_name=entry.external_name,
                        paid=False
                    )
        return payment

groceries/views.py
from datetime import timedelta

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView, SingleObjectMixin

from creditmanagement.models import Transaction
from dining.models import DiningList
from dining.views import DiningListMixin
from general.mail_control import send_templated_mail
from groceries.forms import PaymentCreateForm
from groceries.models import Payment, PaymentEntry


class PaymentsView(LoginRequiredMixin, TemplateView):
    template_name = 'groceries/payment_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Only pick payments not older than a month
        if 'all' not in self.request.GET:
            payments = Payment.objects.filter(created_at__gt=timezone.now() - timedelta(days=31))
        else:
            payments = Payment.objects.all()

        context.update({
            'pay_entries': PaymentEntry.objects.filter(
                user=self.request.user,
                external_name="",
                payment__in=payments).exclude(payment__receiver=self.request.user).order_by('-payment__created_at'),
            'receive_payments': payments.filter(receiver=self.request.user).order_by('-created_at'),
        })
        return context


class PaymentCreateView(LoginRequiredMixin, UserPassesTestMixin, DiningListMixin, TemplateView):
    template_name = 'groceries/payment_create.html'

    def test_func(self):
        # Business-rule: a dining list owner can always create a reimbursement,
        # even if the dining list is no longer adjustable.
        #
        # This is fine because the payer (not the receiver) always has to
        # initiate the payment.
        dining_list = self.get_object()  # type: DiningList
        return dining_list.is_owner(self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        dining_list = self.get_object()

        # Use earlier payment for initial info
        previous = Payment.objects.filter(receiver=self.request.user).order_by('created_at').last()
        if previous:
            initial = {
                'payment_link': previous.payment_link,
                'remarks': previous.remarks,
            }
        else:
            initial = None

        context.update({
            'form': PaymentCreateForm(instance=Payment(dining_list=dining_list, receiver=self.request.user),
                                      initial=initial),
        })
        return context

    def post(self, request, *args, **kwargs):
        form = PaymentCreateForm(data=request.POST,
                                 instance=Payment(dining_list=self.get_object(), receiver=self.request.user))
        if form.is_valid():
            with transaction.atomic():
                payment = form.save()  # type: Payment

                # Send mail to all internal users
                internals = [e.user for e in payment.entries.filter(external_name="")]
                send_templated_mail('mail/payment_entry_created', internals, {'payment': payment}, request)

                # Send different mail to externals
                for e in payment.entries.exclude(external_name=""):
                    send_templated_mail(
                        'mail/payment_entry_created_external',
                        e.user,
                        {'payment': payment, 'entry': e},
                        request)
            return redirect('groceries:payment-detail', pk=payment.pk)

        context = self.get_context_data()
        context['form'] = form
        return self.render_to_response(context)


class PaymentDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Payment

    def test_func(self):
        # Can only use this page if user is receiver
        payment = self.get_object()  # type: Payment
        return payment.receiver == self.request.user

    def post(self, request, *args, **kwargs):
        payment = self.get_object()
        entry = get_object_or_404(PaymentEntry,
                                  id=request.POST.get('entry_id'),
                                  payment=payment,  # Can only get entry for this payment
                                  transaction=None)  # And there should be no transaction (bc then paid is always True)
        paid = request.POST.get('paid')
        if paid == 'true':
            entry.paid = True
        elif paid == 'false':
            entry.paid = False
        entry.save()
        # Jump to table
        return redirect(reverse('groceries:payment-detail', kwargs={'pk': payment.pk}) + '#dinerTable')


class PayView(LoginRequiredMixin, SingleObjectMixin, View):
    """POSTing to this view will create a payment transaction for the current user for given Payment.

    Does not allow GET method.
    """
    model = Payment

    def post(self, request, *args, **kwargs):
        payment = self.get_object()  # type: Payment

        # Check if transactions are allowed
        if not payment.allow_transaction:
            return HttpResponseForbidden("Automatic transactions not allowed")

        # Find the entry on the payment for current user, make sure that it has paid=False and no transaction
        entry = get_object_or_404(PaymentEntry, payment=payment, user=request.user, external_name="", paid=False,
                                  transaction=None)

        # Check balance
        #
        # This has a race condition but that's probably not an issue in practice
        if request.user.account.balance < payment.cost_pp:
            return HttpResponseForbidden("Balance insufficient")

        with transaction.atomic():
            # Create payment transaction
            tx = Transaction.objects.create(source=request.user.account,
                                            target=payment.receiver.account,
                                            amount=payment.cost_pp,
                                            description="Groceries payment for {}".format(payment.dining_list),
                                            created_by=request.user)
            # Update entry
            entry.paid = True
            entry.transaction = tx
            entry.save()

            # Send mail to receiver to notify them that diner paid
            send_templated_mail('mail/payment_tx_created',
                                payment.receiver,
                                {'payment': payment, 'entry': entry},
                                request)
        return redirect('groceries:overview')

assets/templates/groceries/payment_create.html
{#{% extends 'base.html' %}#}
{% extends 'dining_lists/dining_slot.html' %}

{% load credit_tags %}

{% block details %}
    <p><a href="{{ dining_list.get_absolute_url }}">← Back to dining list</a></p>
    <h3>Split grocery costs</h3>
    <form action="{% url 'groceries:payment-create' pk=dining_list.pk %}" method="post">
        {% csrf_token %}
        {% include 'snippets/bootstrap_form.html' with horizontal=True fields=form.visible_fields|slice:"0:1" %}
        <div class="form-group row">
            <label for="nrDiners" class="col-sm-2 col-form-label">Number of diners</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="nrDiners"
                       value="{{ dining_list.diners.count }}">
                <small class="form-text text-muted">To change, add or remove diners on the dining list.</small>
            </div>
        </div>
        <div class="form-group row">
            <label for="costPP" class="col-sm-2 col-form-label">Cost per person</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="costPP" value="-">
                <small class="form-text text-muted">Total cost divided by number of diners, rounded up.</small>
            </div>
        </div>
        <h4>Payment info</h4>
        <p>
            All diners will be notified with the provided info.
            The info will be remembered for the next time you create a payment.
        </p>
        {# Only render the payment info fields #}
        {% include 'snippets/bootstrap_form.html' with horizontal=True fields=form.visible_fields|slice:"1:3" %}
        <div class="card mb-3">
            <div class="card-body">
                <p class="card-text">
                    <span class="badge badge-info">New</span>
                    It is possible to let people pay from their account balance to yours. With this option enabled,
                    diners with sufficient balance can choose to transfer the money from their account balance to yours.
                    You can use the increased account balance to pay for dining lists in the future,
                    or you can always withdraw the money from your account.
                </p>
                <p class="card-text">
                    Diners do not have to pay from their account balance if they do not want to, they can always
                    choose to pay via other means instead.
                </p>
            </div>
        </div>
        {% include 'snippets/bootstrap_form.html' with horizontal=True fields=form.visible_fields|slice:"3:4" %}
        <h4>Contact info</h4>
        <p>
            Setting your contact info is helpful in case of payment issues, change it in
            <a href="{% url 'settings_account' %}">account settings</a>.
        </p>
        <div class="form-group row">
            <label for="email" class="col-sm-2 col-form-label">E-mail address</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="email"
                       value="{% if user.email_public %}{{ user.email }}{% else %}-{% endif %}">
            </div>
        </div>
        <div class="form-group row">
            <label for="phoneNumber" class="col-sm-2 col-form-label">Phone number</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="phoneNumber"
                       value="{{ user.phone_number|default:"-" }}">
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Create groceries payment</button>
    </form>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Ugly as hell
            let totalCost = document.getElementById('id_total_cost');
            let costPP = document.getElementById('costPP');

            function setCostPP() {
                if (totalCost.value === '') {
                    costPP.value = '-';
                } else {
                    costPP.value = '€' + (Math.ceil(totalCost.value / {{ dining_list.diners.count }} * 100) / 100).toFixed(2);
                }
            }

            totalCost.addEventListener('input', setCostPP);
            setCostPP();  // Execute once at page load, in case the value was prefilled (e.g. for bound form)
        });
    </script>
{% endblock %}

assets/templates/groceries/payment_detail.html
{% extends 'base.html' %}
{% load credit_tags %}


{% block content %}
    <p><a href="{% url 'groceries:overview' %}">← Grocery splits overview</a></p>
    <h2>Grocery split</h2>
    <div class="row mb-3">
        <div class="col-sm-2"><strong><i class="fas fa-utensils fa-fw"></i> Dining list</strong></div>
        <div class="col-sm-10"><a
                href="{{ payment.dining_list.get_absolute_url }}">{{ payment.dining_list.date|date:"SHORT_DATE_FORMAT" }}</a>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-sm-2"><strong>Cost</strong></div>
        <div class="col-sm-10">{{ payment.total_cost|euro }}</div>
    </div>
    <div class="row mb-3">
    {# TODO: the entries count does not include the receiver, i.e. is 1 too low in case the receiver also joined #}
        <div class="col-sm-2"><strong>Cost per person ({{ payment.entries.count }})</strong></div>
        <div class="col-sm-10">{{ payment.cost_pp|euro }}</div>
    </div>
    <div class="row mb-3">
        <div class="col-sm-2"><strong>Payment link</strong></div>
        <div class="col-sm-10">
            {% if payment.payment_link %}
                <a href="{{ payment.payment_link }}" target="_blank">{{ payment.payment_link }}</a>
            {% else %}-{% endif %}
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-sm-2"><strong>Remarks</strong></div>
        <div class="col-sm-10">{{ payment.remarks|default:"-" }}</div>
    </div>
    <h3>Diners</h3>
    <p>
        Diners who paid using a transaction from their account balance to yours are automatically marked as paid.
        If you need to undo an automatic transaction, create a reversed
        <a href="{% url 'credits:transaction_add' %}">money transfer</a> from your account to theirs, or
        just pay the person back in cash.
    </p>
    <p class="text-muted small">
        Your own dining entry is not shown in the list because you are the recipient of the money.
    </p>
    <table class="table" style="table-layout: fixed;" id="dinerTable">
        <thead>
        <tr>
            <th scope="col">Diner</th>
            <th scope="col">Paid</th>
            <th scope="col">Change</th>
        </tr>
        </thead>
        <tbody>
        {% for entry in payment.entries.all %}
            <tr>
                <td>
                    {% if entry.is_external %}
                        {{ entry.external_name }} <span class="badge badge-secondary">External diner</span>
                    {% else %}
                        {{ entry.user }}
                        {# Contact info #}
                        {% include 'snippets/contact_info_button.html' with user=entry.user %}
                    {% endif %}
                </td>
                <td>
                    {% if entry.paid %}
                        <span class="text-success"><i class="fas fa-check-circle"></i> Paid</span>
                    {% else %}
                        <span class="text-danger"><i class="fas fa-times-circle"></i> Not paid</span>
                    {% endif %}
                </td>
                <td>
                    {% if entry.transaction %}
                        <span class="text-secondary">Paid with account balance</span>
                    {% else %}
                        <form method="post" action="{% url 'groceries:payment-detail' pk=payment.pk %}"
                              class="d-inline-block">
                            {% csrf_token %}
                            <input type="hidden" name="entry_id" value="{{ entry.pk }}">
                            <button type="submit" name="paid"
                                    value="{% if entry.paid %}false{% else %}true{% endif %}"
                                    class="btn btn-{% if entry.paid %}warning{% else %}primary{% endif %} btn-sm">
                                {% if entry.paid %}Set not paid{% else %}Set paid{% endif %}
                            </button>
                        </form>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}